export const wHydrant = {
  type: "FeatureCollection",
  crs: { type: "name", properties: { name: "EPSG:6318" } },
  features: [
    {
      type: "Feature",
      id: 0,
      geometry: {
        type: "Point",
        coordinates: [-80.199103691561291, 25.99972765528441],
      },
      properties: {
        FID: 0,
        OBJECTID: 3877,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00001",
      },
    },
    {
      type: "Feature",
      id: 1,
      geometry: {
        type: "Point",
        coordinates: [-80.20315274302861, 25.999729134827838],
      },
      properties: {
        FID: 1,
        OBJECTID: 3878,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00002",
      },
    },
    {
      type: "Feature",
      id: 2,
      geometry: {
        type: "Point",
        coordinates: [-80.205286520793209, 25.999725642240808],
      },
      properties: {
        FID: 2,
        OBJECTID: 3879,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00003",
      },
    },
    {
      type: "Feature",
      id: 3,
      geometry: {
        type: "Point",
        coordinates: [-80.205562449860949, 26.001776432656175],
      },
      properties: {
        FID: 3,
        OBJECTID: 3880,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00004",
      },
    },
    {
      type: "Feature",
      id: 4,
      geometry: {
        type: "Point",
        coordinates: [-80.203222487350985, 26.001700778132587],
      },
      properties: {
        FID: 4,
        OBJECTID: 3881,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00005",
      },
    },
    {
      type: "Feature",
      id: 5,
      geometry: {
        type: "Point",
        coordinates: [-80.199187486912606, 26.001870441375583],
      },
      properties: {
        FID: 5,
        OBJECTID: 3882,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00006",
      },
    },
    {
      type: "Feature",
      id: 6,
      geometry: {
        type: "Point",
        coordinates: [-80.200739438940758, 26.001122795705204],
      },
      properties: {
        FID: 6,
        OBJECTID: 3883,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00007",
      },
    },
    {
      type: "Feature",
      id: 7,
      geometry: {
        type: "Point",
        coordinates: [-80.199146656021369, 26.000439527742714],
      },
      properties: {
        FID: 7,
        OBJECTID: 3884,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00008",
      },
    },
    {
      type: "Feature",
      id: 8,
      geometry: {
        type: "Point",
        coordinates: [-80.203194449783439, 26.00048892259435],
      },
      properties: {
        FID: 8,
        OBJECTID: 3885,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00009",
      },
    },
    {
      type: "Feature",
      id: 9,
      geometry: {
        type: "Point",
        coordinates: [-80.201701942681296, 25.999595295512712],
      },
      properties: {
        FID: 9,
        OBJECTID: 3886,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00010",
      },
    },
    {
      type: "Feature",
      id: 10,
      geometry: {
        type: "Point",
        coordinates: [-80.199222399715921, 26.001125302666793],
      },
      properties: {
        FID: 10,
        OBJECTID: 3887,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00011",
      },
    },
    {
      type: "Feature",
      id: 11,
      geometry: {
        type: "Point",
        coordinates: [-80.202147589052601, 26.001028574839623],
      },
      properties: {
        FID: 11,
        OBJECTID: 3888,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00012",
      },
    },
    {
      type: "Feature",
      id: 12,
      geometry: {
        type: "Point",
        coordinates: [-80.200242028240524, 25.99958631710038],
      },
      properties: {
        FID: 12,
        OBJECTID: 3889,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00013",
      },
    },
    {
      type: "Feature",
      id: 13,
      geometry: {
        type: "Point",
        coordinates: [-80.200549328242943, 26.000303118700923],
      },
      properties: {
        FID: 13,
        OBJECTID: 3890,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00014",
      },
    },
    {
      type: "Feature",
      id: 14,
      geometry: {
        type: "Point",
        coordinates: [-80.201776235375505, 26.000312429399699],
      },
      properties: {
        FID: 14,
        OBJECTID: 3891,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00015",
      },
    },
    {
      type: "Feature",
      id: 15,
      geometry: {
        type: "Point",
        coordinates: [-80.20060711794369, 26.001719494487496],
      },
      properties: {
        FID: 15,
        OBJECTID: 3892,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00016",
      },
    },
    {
      type: "Feature",
      id: 16,
      geometry: {
        type: "Point",
        coordinates: [-80.201857178622859, 26.001728990512486],
      },
      properties: {
        FID: 16,
        OBJECTID: 3893,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00017",
      },
    },
    {
      type: "Feature",
      id: 17,
      geometry: {
        type: "Point",
        coordinates: [-80.204184821945844, 26.001872489280274],
      },
      properties: {
        FID: 17,
        OBJECTID: 3894,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00018",
      },
    },
    {
      type: "Feature",
      id: 18,
      geometry: {
        type: "Point",
        coordinates: [-80.204244151875713, 26.000431922975078],
      },
      properties: {
        FID: 18,
        OBJECTID: 3895,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00019",
      },
    },
    {
      type: "Feature",
      id: 19,
      geometry: {
        type: "Point",
        coordinates: [-80.205753648299776, 26.000442602046817],
      },
      properties: {
        FID: 19,
        OBJECTID: 3896,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00020",
      },
    },
    {
      type: "Feature",
      id: 20,
      geometry: {
        type: "Point",
        coordinates: [-80.204074910317317, 25.999716103522559],
      },
      properties: {
        FID: 20,
        OBJECTID: 3897,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00021",
      },
    },
    {
      type: "Feature",
      id: 21,
      geometry: {
        type: "Point",
        coordinates: [-80.2068702713009, 26.001781470191521],
      },
      properties: {
        FID: 21,
        OBJECTID: 3898,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00022",
      },
    },
    {
      type: "Feature",
      id: 22,
      geometry: {
        type: "Point",
        coordinates: [-80.20487601878331, 26.001049097846789],
      },
      properties: {
        FID: 22,
        OBJECTID: 3899,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00023",
      },
    },
    {
      type: "Feature",
      id: 23,
      geometry: {
        type: "Point",
        coordinates: [-80.203702488647181, 26.00104158031013],
      },
      properties: {
        FID: 23,
        OBJECTID: 3900,
        FACILITYID: " ",
        INSTALLDAT: null,
        LOCDESC: " ",
        ROTATION: 0,
        MANUFACTUR: " ",
        OPERABLE: 1,
        LASTSERVIC: null,
        ENABLED: 1,
        ACTIVEFLAG: 1,
        OWNEDBY: 1,
        MAINTBY: 1,
        LASTUPDATE: null,
        LASTEDITOR: " ",
        FLOW1: 0,
        FIREID: " ",
        BONNETCOLO: " ",
        MODEL: " ",
        YRMANUF: " ",
        PROJECTNO: " ",
        LIFECYCLE: "Proposed",
        BOLLARDS: " ",
        ADDRESS: " ",
        PLACEMENT: " ",
        TYPE: " ",
        BARRELDIA: 0,
        GPSDATE: null,
        LATITUDE: " ",
        LONGITUDE: " ",
        COMMENTS: " ",
        OLDID1: " ",
        INSTALLYR: " ",
        CROSSSTDIS: 0,
        CROSSSTNAM: " ",
        FIREDIST: " ",
        WATERSOURC: 0,
        MAINSIZE: 0,
        CNTRLVLVDI: " ",
        FLOW2: 0,
        WWTP: "No",
        created_us: " ",
        created_da: null,
        PRJFACID: "05136-FH-00024",
      },
    },
  ],
};
